### ISSUE TITLE
Collaborative session with physics

### ISSUE THREAD

**Issue by Croucks** [maxxfrazer/MultipeerHelper#11]
Hi,
I really wanted to thank you for the effort you put into this, this is really helpful.

What your example (and basically every other RealityKit example but SwiftStrike) did not include is physics.

I set up the collaborative session with your MultipeerHelper and did get the connectivity to work. Both devices can see the blocks placed by the other device. Everything works fine until I add physics. With physics, everything starts to behave strangely. Blocks are jumping around and I will not have the same behavior on both systems.

I then tried to separate host and client, so that only the host places ModelEntities. So I now have a TapGestureRecognizer, that places ARAnchors

```
@objc func handleTap(recognizer: UITapGestureRecognizer){
    let cameraPosition = arView.cameraTransform.matrix
    let translate = float4x4(
        [1,0,0,0],
        [0,1,0,0],
        [0,0,1,0],
        [0,0,-0.4,1]
    )
    let blockPosition = cameraPosition * translate
    
    let arAnchor = ARAnchor(name: "block", transform: blockPosition)
    arView.session.add(anchor: arAnchor)
}
```

And I implemented the delegate method to let the host add a ModelEntity, once an ARAnchor was added:

```
func session(_ session: ARSession, didAdd anchors: [ARAnchor]) {
    for anchor in anchors {
        if anchor.name == "block" {
            
            // Check for host or not
            // If host: add block to the scene
            if isHost {
                let anchorEntity = AnchorEntity(anchor: anchor)
                
                let model = ModelEntity(
                    mesh: .generateBox(size: [0.3, 0.05, 0.2]),
                    materials: [SimpleMaterial(color: .cyan, isMetallic: false)]
                )
                model.generateCollisionShapes(recursive: true)
                model.physicsBody = PhysicsBodyComponent(
                    shapes: model.collision!.shapes,
                    mass: 1,
                    material: .generate(friction: 10, restitution: 0.1),
                    mode: .dynamic
                )
                
                anchorEntity.addChild(model)
                
                anchorEntity.synchronization?.ownershipTransferMode = .autoAccept
                arView.scene.addAnchor(anchorEntity)
            }
        }
    }
}
```

On the host device, everything works fine. But on the physics behave completely different. Blocks are jumping around. I can see, that when I add a new block it seems to try to synchronize both worlds again, and for a short moment on the client system the blocks are at the same place as on the host system, but then the blocks jump out of each other again.

Have you ever faced similar problems? Maybe I am missing something or doing something wrong.

Thanks in advance!

**Comment by maxxfrazer** [comment]
I haven't done anything involving physics with a collaborative session unfortunately - have you checked the SwiftStrike code to see if it's done similarly there?

https://developer.apple.com/documentation/realitykit/swiftstrike_creating_a_game_with_realitykit

**Comment by Croucks** [comment]
Thanks for your answer!
I did have a look into SwiftStrike, but as I am no expert with ARKit I was pretty overwhelmed by the size of the project and could not really understand how the connectivity is managed there. According to the presentation of SwiftStrike it is just four lines of code, but I doubt that.
I guess I need to figure this out myself, it seems like physics in collaborative sessions are not really something, that's used by many.

**Comment by maxxfrazer** [comment]
I think I know which lines you mean, the core lines that set up the session are in this package here:
https://github.com/maxxfrazer/MultipeerHelper/blob/03c269080c629530991f27b40fdb4660630883e5/Sources/MultipeerHelper/MultipeerHelper.swift#L97
I've added a few more bits to check for compatibility etc, but there's no physics specific parts of it unfortunately.
+ I agree, the projects like SwiftStrike are often too bloated with features, making it a bit difficult to use them for building blocks in learning. Albeit amazing code samples.
