### ISSUE TITLE
Problem using RealityComposer

### ISSUE THREAD

**Issue by xinnai** [maxxfrazer/MultipeerHelper#2]
Hi, thank you very much for your work and this help me a lot! Please help me with my code...
I use your code to Connect a rcProject file. I modify the code 
`else if anchor.name == "Anchor for object placement" {
                print("anchor.name:" ,anchor.name )
                self.scene.anchors.append(boxAnchor)
            }`
In my rcProject file ,I have four Notification activities which controlled by a UIButton, each time I click the button,  it will change to the next activity. 
`xxActivity.post()`
Now I can successfully connect this file with two iPhone. But the problem is: when I click button and send this step index to another iPhone, the other iPhone called:
`func receivedData(_ data: Data, _ peer: MCPeerID) {

        guard let myData = try? NSKeyedUnarchiver.unarchivedObject(ofClasses: [NSDictionary.classForKeyedUnarchiver()], from: data) as? Dictionary<String, String> else{
            return
        }
        print("------------receivedStepIndex:", myData)

        if(myData["type"] == "step"){
            xxActivity.post()
        }
    }` 
But this code cause a crash in the rcProject file's code inside. The same error happens in the Offical sample code too.("CreatingACollaborativeSession") 
<img width="852" alt="截屏2019-12-05上午11 02 22" src="https://user-images.githubusercontent.com/23135336/70200249-c0ef0800-174e-11ea-8f55-26c44fadcb2b.png">

Can you help? Thank you!

**Comment by xinnai** [comment]
I did more test and found that this crash only happens when rcProject activities have an animation. If an activity only does hide and appear (without any animations), all things work fine. But if it contains scale, rotate or other animations, this crash will happen. Do you have any ideas? I think it's a bug in RealityComposer but I am not sure...

**Comment by maxxfrazer** [comment]
Hi @xinnai, I'm glad you like this repo!
I don't know what this issue could be, but there are several similar issues on stackoverflow that may help you such as this one potentially?
https://stackoverflow.com/questions/45812121/notificationcenter-bad-access-when-notification-postet

Is that `post` function something you've created or does that come straight from the rcProject?

BTW when sending data; I find it simpler to just use JSONEncoder and JSONDecoder, it can be clearer when debugging than bringing it in as an NSDictionary. See here for an example:
https://medium.com/swift-india/use-of-codable-with-jsonencoder-and-jsondecoder-in-swift-4-71c3637a6c65

**Comment by xinnai** [comment]
That post function comes from the rcProject file so I've no idea, maybe this bug will be fixed by apple some day. 
That's really kind of you to tell me about JSONEncoder and I will improve my code immediately.

BTW I found your code has memory issue and will crash when connectting a big rcProject. I think this because of the high frequency synchronization make a rapid increase of memory. I don't think it's your code's problem but I think I could let you know, thanks again!

**Comment by maxxfrazer** [comment]
@xinnai that's interesting about the memory issue, how big is your rcProject?
Without knowing much about the specific problem, could it be that both users are creating the entire scene and then sending it to each other over synchronization? I've had problems syncing USDZ files over the network and have opened a FB request to Apple. If you can replicate your issue they might help you out by responding to FB, they seem pretty good at responding to RealityKit feedback so far.

**Comment by maxxfrazer** [comment]
@xinnai looks like RealityKit animations work fine, I added one to the example project on the branch `dev`

**Comment by xinnai** [comment]
@maxxfrazer Hi, When I say animations I mean the animations in a rcProject, I will send this problem to Apple. My rcProject is 180MB... Thanks very much for your reply!

**Comment by maxxfrazer** [comment]
I'm going to close this because it seems like it's most likely a RK issue, not an issue with this framework
